// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCGGPvukFiofZkyPpOnlON-B0jWQZeyNq0',
    appId: '1:580973551069:web:d39fd5d631b09a55c9ea34',
    messagingSenderId: '580973551069',
    projectId: 'okrika-app-123-fa20a',
    authDomain: 'okrika-app-123-fa20a.firebaseapp.com',
    storageBucket: 'okrika-app-123-fa20a.firebasestorage.app',
    measurementId: 'G-RT5BZKKNF2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCB-kEh4INc5CiiFBg7qi7Rbd7zCT81UPA',
    appId: '1:580973551069:android:66f47fcd8d104448c9ea34',
    messagingSenderId: '580973551069',
    projectId: 'okrika-app-123-fa20a',
    storageBucket: 'okrika-app-123-fa20a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDA-YF80ZkwWWcqUzKp_qJ-dsedjMMPnIM',
    appId: '1:580973551069:ios:e77503ba74be93ecc9ea34',
    messagingSenderId: '580973551069',
    projectId: 'okrika-app-123-fa20a',
    storageBucket: 'okrika-app-123-fa20a.firebasestorage.app',
    iosBundleId: 'com.example.flutterOkr',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDA-YF80ZkwWWcqUzKp_qJ-dsedjMMPnIM',
    appId: '1:580973551069:ios:e77503ba74be93ecc9ea34',
    messagingSenderId: '580973551069',
    projectId: 'okrika-app-123-fa20a',
    storageBucket: 'okrika-app-123-fa20a.firebasestorage.app',
    iosBundleId: 'com.example.flutterOkr',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCGGPvukFiofZkyPpOnlON-B0jWQZeyNq0',
    appId: '1:580973551069:web:cdc18fd70cb4cb63c9ea34',
    messagingSenderId: '580973551069',
    projectId: 'okrika-app-123-fa20a',
    authDomain: 'okrika-app-123-fa20a.firebaseapp.com',
    storageBucket: 'okrika-app-123-fa20a.firebasestorage.app',
    measurementId: 'G-K7XB48MBTF',
  );
}
